# This is a basic workflow that is manually triggered

name: Composite action with mutable dependency
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  run-composite-action:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - uses: divanix/poc-action/mutable/commit-referenced@37764c1360c95e31a899f576cc12eba96dda02a9
